<a href="https://colab.research.google.com/github/kunalburgul/ChatBot-To-Bargain-Price-For-WooCommerce-Portal/blob/master/Tensorflow/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the most fundamental concepts of tensord using Tensorflow.

Topics Covered: 

- Introduction to Tensors
- Getting information from tensors. 
- Manipulating tensors
- Tensors & Numpy
- Using @tf.function (a way to speedup your regular python function)
- Using GPUs with TensorFlow (or TPUs)
- Exercises to Practise.

## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf 
print(tf.__version__)

2.4.1


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Check a vector  
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of the vector
vector.ndim

1

In [ ]:
# Create a matric (a matrix has more than 1 dimension)
matrix = tf.constant([[6, 1],
                     [5, 8]]) 
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 1],
       [5, 8]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[61., 58.],
                              [11., 21.],
                              [56., 58.]], dtype=tf.float16) # specify  the data type with dtype parameter
another_matrix  

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[61., 58.],
       [11., 21.],
       [56., 58.]], dtype=float16)>

In [ ]:
# Let's check the number of the dimension using ndim
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [15, 16, 17]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [15, 16, 17]]], dtype=int32)>

In [ ]:
# Let's check the dimnetsions 
tensor.ndim

3

What all we have learnt so far

- **Scalar**: A single number
- **Vector**: A number with direction (e.g windspeed and direction)
- **Matrix**: A 2-dimensional array of numbers
- **Tensor**: An n-dimentsional array of numbers 
(where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating the tensors with `tf.Varaible`

In [ ]:
# Creating the same tensor with the th.Varaible() as above
changable_tensor = tf.Variable([10, 7]) 
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Now let's try to change the element in out changable tensor 
changable_tensor[0] = 1 

TypeError: ignored

In [ ]:
# Let's try out the assign() function to change it 
cahngable_tensor[0].assign(1)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 7], dtype=int32)>

In [ ]:
# Now let's  try this on the unchangaable tensor
unchangable_tensor[0].assign(1)

AttributeError: ignored

***Note***: *Rarely in practice we will need to decide whether to use `tf.constant` OR `tf.Variable` to create tensors, as tensorflow does this for you. However, if in doubt, use `tf.consant` and change it later on if needed.* 

### Creating a Random Tensors
 
Random tensors are tensors of some arbitary size which contain random numbers. 

In [ ]:
# Create a two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set the seed for reproducibility 
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

 ### Shuffle the ordere of elements in a tensor
 

In [ ]:
# Shuffle a tensor (valuable for when u want to shuffle ur data inherent order dosen't effects learning)
not_shuffeled = tf.constant([[1, 2],
                             [2 ,3],
                             [4, 5]])
not_shuffeled.ndim

# Shuffle a non-shuffled tensor
tf.random.shuffle(not_shuffeled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5],
       [1, 2]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffeled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 3],
       [1, 2],
       [4, 5]], dtype=int32)>

In [ ]:

tf.random.shuffle(not_shuffeled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [1, 2],
       [2, 3]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffeled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
not_shuffeled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 3],
       [4, 5]], dtype=int32)>

**Exercise:** Read through the TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and pracatise writing 5 random tensors and shuffle them. 

In [ ]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(5,2))
random_3

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284]], dtype=float32)>

In [ ]:
tf.random.shuffle(random_3)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702],
       [-0.7535805 , -0.57166284],
       [ 0.09988727, -0.50998646],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [ ]:
tf.random.shuffle(random_3, seed=21)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284],
       [ 0.07595026, -1.2573844 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(21) # global level random seed 
tf.random.shuffle(random_3, seed=21) # Operational level random seed

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284],
       [ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(21)
tf.random.shuffle(random_3)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.7565803 , -0.06854702],
       [ 0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(22)
tf.random.shuffle(random_3)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7535805 , -0.57166284],
       [ 0.09988727, -0.50998646]], dtype=float32)>

It look like tensorflow has some rules like : 
Its interactions with operation-level seeds is as follows:

1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

2. If the graph-level seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the graph-level seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both graph-level and operation-level seeds explicitly.

3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.

4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

> Rule 4 - It looks like if we want our shuffled tensors to be in the same order, we have got to use the global level random seed as well as the operaitonal level random seed:




### Other ways to make tensors

In [149]:
tf.ones([10, 7]) 

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [151]:
# Create a tensor of all zeros
tf.zeros(shape=(10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into Tensors

- The main difference beteween Numpya arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computating).


In [159]:
# You can also turn numpy arrays in tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # Create a NumPy array betweem 1 and 35
numpy_A

# X = tf.constant(some_matrix) # Capital for matric or tensor
# y = tf.constant(vector) # Non-Capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [162]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting the information from the tensors

When dealing with the tensors we should be probably be aware of the following attributes:

> - **Shape** - The length (number of elements) of each of the dimensions of a tensor. -------- ***tensor.shape***

> - **Rank** - The number of tensor dimensions.A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n. -------- ***tensor.ndim***

> - **Axis or dimension** - A particular dimension of a tensor. -------- ***tensor[0], tensor[:1]...***

> - **Size** - The total number of items in the tensor. -------- ***tf.size(tensor)***

In [163]:
# Createa a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [164]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [165]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [166]:
2 * 3 * 4 * 5

120

In [170]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of the tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of the elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of the tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along the last axis: 5
Total number of the elements in our tensor: 120
